### ISSUE TITLE
Erro Something went wrong

### ISSUE THREAD

**Issue by joabbremer** [1jhock/Koffee-A-Web-based-Personal-Music-Player#1]
Olá, Gostei do seu sistema. Estou fazendo alguns teste no koffee, porem sempre aparece a menssagem "DEV_ERROR_*function: Something went wrong.". Provavelmente isso acontece porque não consegui gerar as tebelas do sistema. Poderia disponibilizar o scrit para criar as tabelas?

**Comment by jhockofalltrades** [comment]
I can do that. But still busy at work. haha, I will do it. Thanks!
