### ISSUE TITLE
Where to connect to the Database?

### ISSUE THREAD

**Issue by PWNYYY** [1jhock/Koffee-A-Web-based-Personal-Music-Player#2]
Hi, 
where can i find the config to connect the webplayer to
my database?

Ty

**Comment by PWNYYY** [comment]
/edit

http://prntscr.com/m2y84j

**Comment by jhockofalltrades** [comment]
> Hi,
> where can i find the config to connect the webplayer to
> my database?
> 
> Ty

`root/application/config/database.php`

**Comment by PWNYYY** [comment]
Hmm, okay
But now i got this Error 

http://prntscr.com/m3cm5e
http://prntscr.com/m3cmcj

**Comment by jhockofalltrades** [comment]
> Hmm, okay
> But now i got this Error
> 
> http://prntscr.com/m3cm5e
> http://prntscr.com/m3cmcj

You can check the network on the of the requests.

**Comment by leozangulo** [comment]
Hi!!!
I cnat find the sql file to create the database... you cant share it??

Thnks!! :D

**Comment by qeba** [comment]
yes ia am looking for sql files too

**Comment by oliverhildner** [comment]
> > Hmm, okay
> > But now i got this Error
> > http://prntscr.com/m3cm5e
> > http://prntscr.com/m3cmcj
> 
> You can check the network on the of the requests.

I had the same problem. The signup-form tries to add a row to the users-table but the database is still empty..
How can I tell the program to initiate the database structure?

**Comment by jhockofalltrades** [comment]
Hi Everyone, sorry i never really updated this. I updated a new version and added the sql file.

**Comment by jhockofalltrades** [comment]
> > > Hmm, okay
> > > But now i got this Error
> > > http://prntscr.com/m3cm5e
> > > http://prntscr.com/m3cmcj
> > 
> > 
> > You can check the network on the of the requests.
> 
> I had the same problem. The signup-form tries to add a row to the users-table but the database is still empty.. How can I tell the program to initiate the database structure?

I've added the .sql file now

**Comment by jhockofalltrades** [comment]
> yes ia am looking for sql files too

I've added the .sql file now

**Comment by jhockofalltrades** [comment]
> Hmm, okay But now i got this Error
> 
> http://prntscr.com/m3cm5e http://prntscr.com/m3cmcj

I've added the .sql file now

**Comment by jhockofalltrades** [comment]
> > > Hmm, okay
> > > But now i got this Error
> > > http://prntscr.com/m3cm5e
> > > http://prntscr.com/m3cmcj
> > 
> > 
> > You can check the network on the of the requests.
> 
> I had the same problem. The signup-form tries to add a row to the users-table but the database is still empty.. How can I tell the program to initiate the database structure?

I've added the SQL file now. Just remove all the data inside sql and follow the instruction.

**Comment by jhockofalltrades** [comment]
> Hi!!! I cnat find the sql file to create the database... you cant share it??
> 
> Thnks!! :D

I've added the sql file now
